### ISSUE TITLE
Installing busted on Windows

### ISSUE THREAD

**Issue by vertti** [lunarmodules/busted#169]
Running `luarocks install busted` on Windows with luarocks 2.0.13 says:

```
Installing http://luarocks.org/repositories/rocks/busted-1.9.0-1.src.rock...

Error: Parse error processing dependency 'lua_cliargs >= 2.0'
```

**Comment by suraj-mandal** [comment]
I am suffering from the same, issue it is still saying,
Parse error processing dependency 'lua_cliargs = 3.0-1'
What should I do?
