### ISSUE TITLE
_TEST is missing

### ISSUE THREAD

**Issue by Lexicality** [lunarmodules/busted#267]
[The website](http://olivinelabs.com/busted/#private) lists that there is a variable `_TEST` that allows you to test your privates. However:

``` lua
describe("_TEST", function()
    it("should not be nil", function()
        assert.is_not_nil(_TEST)
    end)
end)
```

```
-
0 successes / 1 failure / 0 errors / 0 pending : 0.0 seconds
```

I can find very little about this on github, other than @ajacksified commenting that he didn't like it in #56.
Has it been removed? I wanted to use it to run some of the internal helper functions in my module through the wringer.

**Comment by daurnimator** [comment]
> This was removed purposefully. The documentation for v2.0 is incomplete.

> If you want this functionality, you can just set _TEST to true at the beginning of the file as a global. The correct way to address this, in my opinion, is to refactor your code to make it more easily externally testable.

:( I just upgraded to 2.0 and am sad to see the decision made in https://github.com/Olivine-Labs/busted/issues/76#issuecomment-11853565 is reversed. please bring back `_TEST`!
