### ISSUE TITLE
feature request: fancy verbose output

### ISSUE THREAD

**Issue by Habbie** [lunarmodules/busted#274]
like a combination of TAP and the default (utfTerminal) with the colored dots. Perhaps tie it to -vv ('doubly verbose'), or a new output type.

(as discussed on #lua with @ajacksified)

**Comment by justinmk** [comment]
https://github.com/Olivine-Labs/busted/pull/394 somewhat addressed this, but if anyone is interested, we have a new handler in Neovim that definitely addresses this request:

https://github.com/neovim/neovim/blob/master/busted/outputHandlers/nvim.lua

**Comment by alerque** [comment]
I came along to open an issue for this as well and found it has already been opened.

For reference  the updated link for the output NeoVim output handler is here now: https://github.com/neovim/neovim/blob/master/test/busted/outputHandlers/nvim.lua

My input on this would be that [Mocha](https://mochajs.org/)'s output is much nicer in this regard. With Busted you don't get any information about _passing_ tests, just a dot and a count. Errors output is fine, but it doesn't even print out a list of what was being tested. You have to read the code and find the `describe()` and `it()` lines.

With Mocha you get a descriptive list of what passed that looks like this:

```
  fluent helper
    ✓ should take a key and return for the default language
    ✓ should take a key with an attribute and return
    ✓ should take a key that uses context data and return
    ✓ should take a key that uses context data and and override value and return
    ✓ should take a key and return for the override language

  errors:
    ✓ should throw an error when an invalid key is passed:
    ✓ should throw an error when no language is undefined.
    ✓ should throw an error when the given property is missing.


  8 passing (22ms)
```

**Comment by justinmk** [comment]
> With Mocha you get a descriptive list of what passed that looks like this:

@alerque which output handlers did you try? That already happens with TAP, gtest, and Nvim handlers. Sounds like you have only tried the default handler.

**Comment by alerque** [comment]
I'm going to close this because as far as I an tell from the initial issue, the later addition of the `gtest` output handler should have closed this. Upstreaming the `nvim` output handler is certainly something we could consider too but should be tracked in another issue.
