### ISSUE TITLE
Lua “busted.runner” must be on every file

### ISSUE THREAD

**Issue by ktalebian** [lunarmodules/busted#586]
I have a tests.setup.lua file that I want to use to initialize and register custom matchers. It looks like

```lua
-- tests.setup.lua
package.path = package.path .. ';../?.lua'

require 'busted.runner'()

require 'tests.mocks.ngx'
require 'tests.extensions.matchers'
require 'tests.extensions.spy'
```

Then a test file would have

```lua
package.path = package.path .. ';../?.lua'
require 'tests.setup'
```

However, running lua the-testfile.lua will not run any tests unless I specifically add `require 'busted.runner'()` to that file as well. Why is requiring it from tests.setup not enough?

**Comment by Tieske** [comment]
my guess is because of the busted test-sandbox.

When requiring a module top-level, eg. first line:

```lua
local url = require('socket.url')
```

The `url` variable is available in all the tests and handlers as an upvalue. Despite that busted will scrap the loaded modules from `package.loaded`.

So I'd expect this to work:

```lua
describe("here goes with my tests", function()

  setup(function()
    package.path = package.path .. ';../?.lua'
    require 'tests.setup'
  end)

  it("can now test my stuff", function()
    -- test your stuff here
  end)
end)
```

**Comment by ktalebian** [comment]
@Tieske but this isn't really helping me, because `describe` would not be available if I don't include `require 'busted.runner'()` at the top of the page.

**Comment by Tieske** [comment]
what command line do you use to execute your testfile?

We use a similar approach, in testfiles we require our test helpers, see https://github.com/Kong/kong/blob/master/spec/02-integration/04-admin_api/01-admin_api_spec.lua#L1

Which load custom assertions https://github.com/Kong/kong/blob/master/spec/helpers.lua#L654

**Comment by ktalebian** [comment]
@Tieske I use `resty` (or `lua`) so running the tests as standalone, hence why I need the runner included.

**Comment by Tieske** [comment]
so do we, see https://github.com/Kong/kong/blob/master/bin/busted

**Comment by EricFedrowisch** [comment]
Maybe this would help?
https://github.com/Olivine-Labs/busted/issues/571

**Comment by alerque** [comment]
@ktalebian I think you're missing how Lua is scoping variables here. Just running `require` on something does not necessarily stuff anything into the global scope. Of course some things you can load will do that, but busted does not. When you `require('busted.runner')` it returns a function, which you are then running. That adds some stuff to the current caller context, but not to the global context. Hence when you require that file from another place, the context where busted is setup is that of your setup file, not the global scope. You can't then expect to access them from the global scope.

You could export them with something like:

```lua
_G["describe"] = describe
```

... but I have no idea how deep that rabbit hole would take you. Frankly it sounds like you are trying to run things inside out. If you want to use busted as a library. I suggest starting from the outside working in not the other way around. See #482 for some discussion along those lines.

Happy to re-evaluate if I've misunderstood something.
