### ISSUE TITLE
confusing behavior of spy matcher

### ISSUE THREAD

**Issue by StarlightIbuki** [lunarmodules/busted#682]
```lua
local function contain(state, arguments)
  local expected = arguments[1]
  return function(value)
    return type(value) == "string" and value:find(expected)
  end
end

assert:register("matcher", "contain", contain)

print(matcher.contain("string")("substring")) -- false
```

It turns out matcher treats all non-true values as false. It should be written like `type(value) == "string" and value:find(expected) and true`.

If this is expected, it should be documented. I did not find where to create PR or submit patches for [documentation](http://olivinelabs.com/busted/#asserts).

There's also a typo ["you should should"](http://olivinelabs.com/busted/#asserts:~:text=was_called_with%2C%20you-,should%20should,-use%20match.is_ref).

**Comment by Tieske** [comment]
The documentation is in the `gh-pages` branch
