### ISSUE TITLE
Link to official docs broken

### ISSUE THREAD

**Issue by gotschmarcel-ni** [lunarmodules/busted#690]
The link results in a 404 page. [http://olivinelabs.com/busted](http://olivinelabs.com/busted)

**Comment by x4ku** [comment]
Looks like this is where the documentation lives now:

https://lunarmodules.github.io/busted/

**Comment by Tieske** [comment]
the repo moved and so did the docs. There might be a redirect put in place...

**Comment by gotschmarcel-ni** [comment]
Thanks!
