### ISSUE TITLE
Question: Splitting tests into multiple files

### ISSUE THREAD

**Issue by PerMalmberg** [lunarmodules/busted#702]
Hi,

Is it possible to split tests into multiple files such that I have some common `expose` in a file that is `required` from the actual tests files?

My case is that I have an external API that I want to create mocks/stubs for, but I don't want to do this in every single spec-file. 

I tried to do the following as a test:

test_expose.lua
```
expose("some globals", function()
    _G.library = { getCoreUnit = function() return {}  end}
    _G.unit = {}
end)
```

```
require("test_expose")

describe("Point", function()
    it("runs", function()

    end)
end
```

The above gives this error when running 

> suite ./src/flight/route/Point_spec.lua
./src/flight/route/test_expose.lua:2: attempt to call a nil value (global 'expose')
stack traceback:
        ./src/flight/route/test_expose.lua:2: in main chunk

Can I require parts of busted to make this work?

**Comment by Tieske** [comment]
using "require" will cache the results of that module I believe. Have you tried wrapping it in a function?

test_expose.lua
```lua
return function()
    expose("some globals", function()
        _G.library = { getCoreUnit = function() return {}  end}
        _G.unit = {}
    end)
end
```

in your tests;
```lua
require("test_expose")()    --> note the extra () to call the function

describe("Point", function()
    it("runs", function()

    end)
end
```

**Comment by PerMalmberg** [comment]
Oh, ofc. Thanks you.
