### ISSUE TITLE
Async not functional? (attempt to call a nil value (global 'async'))

### ISSUE THREAD

**Issue by PerMalmberg** [lunarmodules/busted#703]
Hi,

Is async functional or not? All I get is this:

> attempt to call a nil value (global 'async')

I found this very old thread suggesting it wasn't supported in v2 for a while, but there are also tests for async in this repo.
https://github.com/lunarmodules/busted/issues/545

This is my install script
```
sudo apt install npm sudo apt lua5.3 liblua5.3-dev libev-dev luarocks -y
# Install rocks system wide as in a local installation busted can't find luacov
sudo luarocks install copas
sudo luarocks install lua-ev scm --server=http://luarocks.org/repositories/rocks-scm/
sudo luarocks install moonscript
sudo luarocks install busted
sudo luarocks install luacov
sudo luarocks install luacov-html
```

**Comment by Tieske** [comment]
not functional

**Comment by PerMalmberg** [comment]
In that case you should probably remove it from the documentation to save everyone some time. :)

**Comment by Tieske** [comment]
there used to be a branch with a 2.0 implementatioin (wip level), but can't seem to find it anymore...
