### ISSUE TITLE
Wrong `LUAROCKS_SYSCONFDIR` in `busted.bat`

### ISSUE THREAD

**Issue by ZzZombo** [lunarmodules/busted#717]
It has the line of `set "LUAROCKS_SYSCONFDIR=C:\Program Files/luarocks"` which doesn't point to the LuaRocks installation on my system because it's installed to a different location.

**Comment by Tieske** [comment]
That's a LuaRocks issue, since the wrapper script is generated by LuaRocks. Please report it there.
