### ISSUE TITLE
[question] how to pass argument to function when trying to catch errors

### ISSUE THREAD

**Issue by mb6ockatf** [lunarmodules/busted#725]
```lua
describe("some asserts", function()
	it("should throw an error", function()
		assert.has_error(function throw_error() error("Yup,  it errored") end)
	end)
end)
```

here's a slightly modified example taken from [official documentation](https://lunarmodules.github.io/busted/#asserts). what if i want to pass arguments to function thow_error? how do i do that?

**Comment by alerque** [comment]
Wrap in in another function so that the function you pass to assert has all the function calls as you wish them to appear (passing any args to the actual functions that need testing):

```lua
local function throws_error(your, args, here)
	-- does something with args
	error("Yup,  it errored")
end
describe("some asserts", function()
	it("should throw an error", function()
		local function tester () throws_error(your, args, here) end
		assert.has_error(tester)
	end)
end)
```

**Comment by mb6ockatf** [comment]
thank you much! :smile:
