### ISSUE TITLE
Teee

### ISSUE THREAD

**Issue by LUCAS09J** [lunarmodules/busted#741]
- nombre: Lua reventada
                usos: lunarmodules/busted@v2.2.0
            # Run on an entire project
$ docker run -v "$(pwd):/data" ghcr.io/lunarmodules/busted:latest

# Run on one directory:
$ docker run -v "$(pwd):/data" ghcr.io/lunarmodules/busted:latest specs

**Comment by alerque** [comment]
What is the purpose of this issue?
