### ISSUE TITLE
How to work with luajit and ffi ?

### ISSUE THREAD

**Issue by qiuxinyun2010** [lunarmodules/busted#744]
1.test_spec.lua
```
describe("test", function()
    it("testTrue", function()
        assert.True(1 == 1)
      end)
end)
```
run: `busted test_spec.lua`
noError

2.test_ffi_spec.lua
```
describe("test", function()
    it("testTrue", function()
        local ffi = require "ffi"
        assert.True(1 == 1)
      end)
end)
```
run: `busted test_ffi_spec.lua`
errors: `/usr/bin/lua5.1: [string "require 'ffi'"]:1: module 'ffi' not found:No LuaRocks module found for ffi`

run: `busted test_ffi_spec.lua --lua=luajit`
errors: `luajit: ...uarocks/lib/luarocks/rocks-5.1/busted/2.2.0-1/bin/busted:3: module 'busted.runner' not found:`

**Comment by masakk1** [comment]
You marked this as closed. But what is the solution?
