### ISSUE TITLE
No coverage report when setting lua interpreter in `.busted`

### ISSUE THREAD

**Issue by sammyshear** [lunarmodules/busted#747]
I am trying to use busted to test a new Neovim plugin and I wanted to generate code coverage with `luacov`. This all works fine if I use the command `busted -c --lua='nlua'` while not specifying the lua interpreter option in the busted config file. Unfortunately, regardless of what command I run, if the lua interpreter is set in the config file, this doesn't work.

Here is the very basic config file:
```
return {
  _all = {
    lpath = 'lua/?.lua;lua/?/init.lua',
    lua = 'nlua',
  },
}
```

I am not sure why this is the case, but it is just a bit of a pain that I can't use the config file to make my life a little simpler.

**Comment by sammyshear** [comment]
After a little more investigating it looks like this is actually a problem with `nlua`. The stats seemed to actually be generating when I accidentally ran the command without `--lua=nlua` and the tests failed because I was missing `nlua`.

**Comment by Tieske** [comment]
I don't think I've seen the `_all` key in your config file before... If I look at `penlight` for example, it is called `default`.

Here's the full Penlight file:
```lua
return {
  default = {
    verbose = true,
    output = "gtest",
    lpath = "./lua/?.lua;./lua/?/init.lua",
  }
}
```
